### ISSUE TITLE
Problems in the code

### ISSUE THREAD

**Issue by bfmike** [squix78/MAX7219LedMatrix#1]
Hi,

You are using SPI_MODE3, but the device is actually SPI_MODE0 (probably worked originally because SPI_MODE3 isn't/wasn't supported.

You are also setting a C++ String object to NULL which isn't allowed.  The easiest thing to do is set it to an empty string and then check the length.

Finally, the example "AnimateText" works fine, but the example in the README.md is a bit broken between the constructor and that .init() method.  The following "git diff" shows the fixes for the library.

Many thanks for your work as I've found it very useful!

Mike

diff --git a/LedMatrix.cpp b/LedMatrix.cpp
index ec1f18c..b092dae 100644
--- a/LedMatrix.cpp
+++ b/LedMatrix.cpp
@@ -17,7 +17,7 @@ void LedMatrix::init() {
   pinMode(mySlaveSelectPin, OUTPUT);

   SPI.begin ();
-  SPI.setDataMode(SPI_MODE3);
-  SPI.setDataMode(SPI_MODE0);
  SPI.setClockDivider(SPI_CLOCK_DIV128);
  for(byte device = 0; device < myNumberOfDevices; device++) {
   sendByte (device, MAX7219_REG_SCANLIMIT, 7);   // show all 8 digits
  @@ -117,9 +117,9 @@ void LedMatrix::scrollTextRight() {
  }
  void LedMatrix::scrollTextLeft() {
    myTextOffset = (myTextOffset - 1) % ((int)myText.length() \* myCharWidth + myNumberOfDevices \* 8);
-   if (myTextOffset == 0 && myNextText != NULL) {
-   if (myTextOffset == 0 && myNextText.length() > 0) {
     myText = myNextText;
-      myNextText = NULL;
-      myNextText = "";
     calculateTextAlignmentOffset();
  }
  }

**Comment by marcelstoer** [comment]
The diff you posted (thanks btw!) would be a lot more helpful for others if you put it into a block that isn't processed as Markdown (e.g. try ``` on the lines before and after).
